# -*- coding: utf-8 -*-
"""English-to-French Translation chatbot.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15WrTEXH8IZp3gpsLW2Z7P1pTtJDfToUU

#**English-to-French Translation chatbot**
"""

!pip install -U transformers sentencepiece torch

from transformers import AutoTokenizer, AutoModelForSeq2SeqLM

model_name = "Helsinki-NLP/opus-mt-en-fr"

tokenizer = AutoTokenizer.from_pretrained(model_name)
model = AutoModelForSeq2SeqLM.from_pretrained(model_name)

text = "Hello world"

inputs = tokenizer(text, return_tensors="pt")
outputs = model.generate(**inputs)

translation = tokenizer.decode(outputs[0], skip_special_tokens=True)

print("English:", text)
print("French:", translation)

def translate_to_french(text):
    inputs = tokenizer(text, return_tensors="pt")
    outputs = model.generate(**inputs)
    return tokenizer.decode(outputs[0], skip_special_tokens=True)

print("English to French Translation Chatbot")
print("Type 'exit' to stop.\n")

while True:
    user_input = input("You (English): ")

    if user_input.lower() == "exit":
        print("Chatbot: Goodbye!")
        break

    french_text = translate_to_french(user_input)
    print("French:", french_text)